# Generated by Django 3.1.3 on 2021-01-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
                ('price', models.IntegerField()),
                ('author', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('year', models.DateField()),
                ('created_at', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
